version: 2

build:
  os: ubuntu-20.04
  tools:
    python: 3.11

sphinx:
  configuration: usermanual/source/conf.py

formats:
  - pdf

python:
  version: "3.11"
  install:
    - requirements: docs/requirements.txt
